### ISSUE TITLE
Enhancement Request:  Filtering on VPC stratification 

### ISSUE THREAD

**Issue by DuyTran16** [cran/tidyvpc#1]
I would like to request feature to tidyvpc to be able to filter on VPC stratification.  For example, a vpc was stratify by covariate "study" in tidyvpc, but only want specific study to be outputted when plotting the vpc object.

Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and potentially URLs in the `DESCRIPTION` file. Thanks!
